apiVersion: v1
kind: Service
metadata:
  name: price-alerts-api
  namespace: price-alerts
spec:
  type: ClusterIP
  selector:
    app: price-alerts-api
  ports:
    - name: http
      port: 80
      targetPort: http
