apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: price-alerts-api
  namespace: price-alerts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: price-alerts-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
